TIM-465 Modify types for mode of payment
TimBuilding/wisecare pull request #189
Opened 2024-10-21 00:24 UTC by tamrivera05

2024-10-21 00:24 UTC, tamrivera05 commented
* **#189** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/189?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tamrivera05 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-21 01:07 UTC, xdjeremy requested changes

2024-10-21 01:07 UTC, xdjeremy commented on src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/billing-statements.tsx
> +  console.log(billings)
Clean up console.log

2024-10-23 11:48 UTC, tamrivera05 commented on src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/billing-statements.tsx
> +  console.log(billings)
k na

2024-10-23 11:52 UTC, xdjeremy approved these changes

2024-10-23 11:54 UTC, merged