TIM-507 Improve formatting on Company Profile
TimBuilding/wisecare pull request #240
Opened 2024-10-27 14:28 UTC by tamrivera05

2024-10-27 14:28 UTC, tamrivera05 commented
* **#240** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/240?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tamrivera05 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-27 14:42 UTC, xdjeremy requested changes

2024-10-27 14:42 UTC, xdjeremy commented on src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(billing statements)/billing-information.tsx
> +            {data.amount ? formatCurrency(data.amount) : 'N/A'}
Follow the design of other null valued details

![Screenshot 2024-10-27 at 10.41.59 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OlfUCaLtm86TKPMIs0RY/41bbc1ad-6b01-4290-ad8f-1b9b1eaee915.png)

2024-10-27 15:27 UTC, tamrivera05 commented on src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(billing statements)/billing-information.tsx
> +            {data.amount ? formatCurrency(data.amount) : 'N/A'}
k na pu mwa

2024-10-28 00:52 UTC, xdjeremy approved these changes

2024-10-28 00:56 UTC, merged