TIM-561 Employee Card Number should be included in the employees table
TimBuilding/wisecare pull request #276
Opened 2024-10-31 07:25 UTC by tamrivera05

2024-10-31 07:25 UTC, tamrivera05 commented
* **#276** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/276?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tamrivera05 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-31 09:44 UTC, xdjeremy requested changes

2024-10-31 09:44 UTC, xdjeremy commented on src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-columns.tsx
> +    cell: ({ row }) => (
Use `accessorFn` instead of `cell`.
This makes the column searchable

2024-10-31 09:45 UTC, xdjeremy requested changes

2024-10-31 09:45 UTC, xdjeremy commented on src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-columns.tsx
> +    cell: ({ row }) => (
Also, remove some columns to make space for this

2024-11-03 02:59 UTC, xdjeremy approved these changes

2024-11-03 03:02 UTC, merged