TIM-601 feat(employees): refactor to submit to pending_company_employees table
TimBuilding/wisecare pull request #308
Opened 2024-11-03 13:20 UTC by xdjeremy

2024-11-03 13:20 UTC, xdjeremy commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/308?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#308** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/308?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#307** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/307?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @xdjeremy and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-04 02:46 UTC, tamrivera05 approved these changes

2024-11-04 02:50 UTC, tamrivera05 requested changes
restack

2024-11-04 03:06 UTC, tamrivera05 approved these changes

2024-11-04 03:32 UTC, merged