TIM-714 fix(employees): parsing of date for import
TimBuilding/wisecare pull request #389
Opened 2024-11-11 13:46 UTC by xdjeremy

2024-11-11 13:46 UTC, xdjeremy commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/389?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#389** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/389?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#388** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/388?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#387** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/387?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#386** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/386?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @xdjeremy and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-11 15:13 UTC, tamrivera05 approved these changes

2024-11-11 15:23 UTC, tamrivera05 requested changes
ci test failed

2024-11-12 07:48 UTC, tamrivera05 approved these changes

2024-11-12 07:52 UTC, merged